In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_test = pd.read_csv("/Users/fesavaskurt/Python&ML/Kodlarım/Python/datasets/ML Datasets/biketest.csv")
df_train = pd.read_csv("/Users/fesavaskurt/Python&ML/Kodlarım/Python/datasets/ML Datasets/biketrain.csv")

In [3]:
df_train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

In [4]:
df_train.shape

(10886, 12)

In [5]:
df_train = df_train.drop(columns=["casual", "registered"])

In [6]:
df_train["datetime"].unique

<bound method Series.unique of 0        2011-01-01 00:00:00
1        2011-01-01 01:00:00
2        2011-01-01 02:00:00
3        2011-01-01 03:00:00
4        2011-01-01 04:00:00
                ...
10881    2012-12-19 19:00:00
10882    2012-12-19 20:00:00
10883    2012-12-19 21:00:00
10884    2012-12-19 22:00:00
10885    2012-12-19 23:00:00
Name: datetime, Length: 10886, dtype: object>

In [10]:
df_train["datetime"] = pd.to_datetime(df_train["datetime"])

In [11]:
df_train["datetime"] = pd.to_datetime(df_train["datetime"])

In [12]:
df_train["hour"] = df_train["datetime"].dt.hour
df_train["weekday"] = df_train["datetime"].dt.weekday
df_train["month"] = df_train["datetime"].dt.month
df_train["year"] = df_train["datetime"].dt.year

In [13]:
df_train.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,hour,weekday,month,year
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,16,0,5,1,2011
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,40,1,5,1,2011
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,32,2,5,1,2011
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,13,3,5,1,2011
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,1,4,5,1,2011

In [33]:
season_dummies = pd.get_dummies(df_train['season'], prefix='season', drop_first=True)

In [34]:
season_dummies

       season_2  season_3  season_4
0         False     False     False
1         False     False     False
2         False     False     False
3         False     False     False
4         False     False     False
...         ...       ...       ...
10881     False     False      True
10882     False     False      True
10883     False     False      True
10884     False     False      True
10885     False     False      True

[10886 rows x 3 columns]

In [35]:
df_train = pd.concat([df_train, season_dummies], axis=1)

In [36]:
df_train

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,hour,weekday,month,year,season_2,season_3,season_4
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0000,16,0,5,1,2011,False,False,False
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0000,40,1,5,1,2011,False,False,False
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0000,32,2,5,1,2011,False,False,False
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0000,13,3,5,1,2011,False,False,False
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0000,1,4,5,1,2011,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10881,2012-12-19 19:00:00,4,0,1,1,15.58,19.695,50,26.0027,336,19,2,12,2012,False,False,True
10882,2012-12-19 20:00:00,4,0,1,1,14.76,17.425,57,15.0013,241,20,2,12,2012,False,False,True
10883,2012-12-19 21:00:00,4,0,1,1,13.94,15.910,61,15.0013,168,21,2,12,2012,False,False,True
10884,2012-12-19 22:00:00,4,0,1,1,13.94,17.425,61,6.0032,129,22,2,12,2012,False,False,True
10885,2012-12-19 23:00:00,4,0,1,1,13.12,16.665,66,8.9981,88,23,2,12,2012,False,False,True