In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/Users/fesavaskurt/Python&ML/Kodlarım/Projects/Home-Credit-Default-Risk-Project.ipynb/application_train.csv")

In [3]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

### Dataset İncelemesi

In [4]:
df.shape

(307511, 122)

In [5]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 122 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    SK_ID_CURR                    307511 non-null  int64
 1    TARGET                        307511 non-null  int64
 2    NAME_CONTRACT_TYPE            307511 non-null  object
 3    CODE_GENDER                   307511 non-null  object
 4    FLAG_OWN_CAR                  307511 non-null  object
 5    FLAG_OWN_REALTY               307511 non-null  object
 6    CNT_CHILDREN                  307511 non-null  int64
 7    AMT_INCOME_TOTAL              307511 non-null  float64
 8    AMT_CREDIT                    307511 non-null  float64
 9    AMT_ANNUITY                   307499 non-null  float64
 10   AMT_GOODS_PRICE               307233 non-null  float64
 11   NAME_TYPE_SUITE               306219 non-null  object
 12   NAME_INCOME_TYPE              307511 non-null  object
 13   NAME_EDUCATION_TYPE           307511 non-null  object
 14   NAME_FAMILY_STATUS            307511 non-null  object
 15   NAME_HOUSING_TYPE             307511 non-null  object
 16   REGION_POPULATION_RELATIVE    307511 non-null  float64
 17   DAYS_BIRTH                    307511 non-null  int64
 18   DAYS_EMPLOYED                 307511 non-null  int64
 19   DAYS_REGISTRATION             307511 non-null  float64
 20   DAYS_ID_PUBLISH               307511 non-null  int64
 21   OWN_CAR_AGE                   104582 non-null  float64
 22   FLAG_MOBIL                    307511 non-null  int64
 23   FLAG_EMP_PHONE                307511 non-null  int64
 24   FLAG_WORK_PHONE               307511 non-null  int64
 25   FLAG_CONT_MOBILE              307511 non-null  int64
 26   FLAG_PHONE                    307511 non-null  int64
 27   FLAG_EMAIL                    307511 non-null  int64
 28   OCCUPATION_TYPE               211120 non-null  object
 29   CNT_FAM_MEMBERS               307509 non-null  float64
 30   REGION_RATING_CLIENT          307511 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 33   HOUR_APPR_PROCESS_START       307511 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 40   ORGANIZATION_TYPE             307511 non-null  object
 41   EXT_SOURCE_1                  134133 non-null  float64
 42   EXT_SOURCE_2                  306851 non-null  float64
 43   EXT_SOURCE_3                  246546 non-null  float64
 44   APARTMENTS_AVG                151450 non-null  float64
 45   BASEMENTAREA_AVG              127568 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 47   YEARS_BUILD_AVG               103023 non-null  float64
 48   COMMONAREA_AVG                92646 non-null   float64
 49   ELEVATORS_AVG                 143620 non-null  float64
 50   ENTRANCES_AVG                 152683 non-null  float64
 51   FLOORSMAX_AVG                 154491 non-null  float64
 52   FLOORSMIN_AVG                 98869 non-null   float64
 53   LANDAREA_AVG                  124921 non-null  float64
 54   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 55   LIVINGAREA_AVG                153161 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 57   NONLIVINGAREA_AVG             137829 non-null  float64
 58   APARTMENTS_MODE               151450 non-null  float64
 59   BASEMENTAREA_MODE             127568 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 61   YEARS_BUILD_MODE              103023 non-null  float64
 62   COMMONAREA_MODE               92646 non-null   float64
 63   ELEVATORS_MODE                143620 non-null  float64
 64   ENTRANCES_MODE                152683 non-null  float64
 65   FLOORSMAX_MODE                154491 non-null  float64
 66   FLOORSMIN_MODE                98869 non-null   float64
 67   LANDAREA_MODE                 124921 non-null  float64
 68   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 69   LIVINGAREA_MODE               153161 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 71   NONLIVINGAREA_MODE            137829 non-null  float64
 72   APARTMENTS_MEDI               151450 non-null  float64
 73   BASEMENTAREA_MEDI             127568 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 75   YEARS_BUILD_MEDI              103023 non-null  float64
 76   COMMONAREA_MEDI               92646 non-null   float64
 77   ELEVATORS_MEDI                143620 non-null  float64
 78   ENTRANCES_MEDI                152683 non-null  float64
 79   FLOORSMAX_MEDI                154491 non-null  float64
 80   FLOORSMIN_MEDI                98869 non-null   float64
 81   LANDAREA_MEDI                 124921 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 83   LIVINGAREA_MEDI               153161 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 85   NONLIVINGAREA_MEDI            137829 non-null  float64
 86   FONDKAPREMONT_MODE            97216 non-null   object
 87   HOUSETYPE_MODE                153214 non-null  object
 88   TOTALAREA_MODE                159080 non-null  float64
 89   WALLSMATERIAL_MODE            151170 non-null  object
 90   EMERGENCYSTATE_MODE           161756 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 96   FLAG_DOCUMENT_2               307511 non-null  int64
 97   FLAG_DOCUMENT_3               307511 non-null  int64
 98   FLAG_DOCUMENT_4               307511 non-null  int64
 99   FLAG_DOCUMENT_5               307511 non-null  int64
 100  FLAG_DOCUMENT_6               307511 non-null  int64
 101  FLAG_DOCUMENT_7               307511 non-null  int64
 102  FLAG_DOCUMENT_8               307511 non-null  int64
 103  FLAG_DOCUMENT_9               307511 non-null  int64
 104  FLAG_DOCUMENT_10              307511 non-null  int64
 105  FLAG_DOCUMENT_11              307511 non-null  int64
 106  FLAG_DOCUMENT_12              307511 non-null  int64
 107  FLAG_DOCUMENT_13              307511 non-null  int64
 108  FLAG_DOCUMENT_14              307511 non-null  int64
 109  FLAG_DOCUMENT_15              307511 non-null  int64
 110  FLAG_DOCUMENT_16              307511 non-null  int64
 111  FLAG_DOCUMENT_17              307511 non-null  int64
 112  FLAG_DOCUMENT_18              307511 non-null  int64
 113  FLAG_DOCUMENT_19              307511 non-null  int64
 114  FLAG_DOCUMENT_20              307511 non-null  int64
 115  FLAG_DOCUMENT_21              307511 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [6]:
df["SK_ID_CURR"].nunique()

307511

In [7]:
df["TARGET"].value_counts(normalize= True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [8]:
pd.set_option("display.max_rows", None)

(df.isnull().mean() * 100).sort_values(ascending=False)

COMMONAREA_MEDI                 69.872297
COMMONAREA_AVG                  69.872297
COMMONAREA_MODE                 69.872297
NONLIVINGAPARTMENTS_MODE        69.432963
NONLIVINGAPARTMENTS_AVG         69.432963
NONLIVINGAPARTMENTS_MEDI        69.432963
FONDKAPREMONT_MODE              68.386172
LIVINGAPARTMENTS_MODE           68.354953
LIVINGAPARTMENTS_AVG            68.354953
LIVINGAPARTMENTS_MEDI           68.354953
FLOORSMIN_AVG                   67.848630
FLOORSMIN_MODE                  67.848630
FLOORSMIN_MEDI                  67.848630
YEARS_BUILD_MEDI                66.497784
YEARS_BUILD_MODE                66.497784
YEARS_BUILD_AVG                 66.497784
OWN_CAR_AGE                     65.990810
LANDAREA_MEDI                   59.376738
LANDAREA_MODE                   59.376738
LANDAREA_AVG                    59.376738
BASEMENTAREA_MEDI               58.515956
BASEMENTAREA_AVG                58.515956
BASEMENTAREA_MODE               58.515956
EXT_SOURCE_1                    56.381073
NONLIVINGAREA_MODE              55.179164
NONLIVINGAREA_AVG               55.179164
NONLIVINGAREA_MEDI              55.179164
ELEVATORS_MEDI                  53.295980
ELEVATORS_AVG                   53.295980
ELEVATORS_MODE                  53.295980
WALLSMATERIAL_MODE              50.840783
APARTMENTS_MEDI                 50.749729
APARTMENTS_AVG                  50.749729
APARTMENTS_MODE                 50.749729
ENTRANCES_MEDI                  50.348768
ENTRANCES_AVG                   50.348768
ENTRANCES_MODE                  50.348768
LIVINGAREA_AVG                  50.193326
LIVINGAREA_MODE                 50.193326
LIVINGAREA_MEDI                 50.193326
HOUSETYPE_MODE                  50.176091
FLOORSMAX_MODE                  49.760822
FLOORSMAX_MEDI                  49.760822
FLOORSMAX_AVG                   49.760822
YEARS_BEGINEXPLUATATION_MODE    48.781019
YEARS_BEGINEXPLUATATION_MEDI    48.781019
YEARS_BEGINEXPLUATATION_AVG     48.781019
TOTALAREA_MODE                  48.268517
EMERGENCYSTATE_MODE             47.398304
OCCUPATION_TYPE                 31.345545
EXT_SOURCE_3                    19.825307
AMT_REQ_CREDIT_BUREAU_HOUR      13.501631
AMT_REQ_CREDIT_BUREAU_DAY       13.501631
AMT_REQ_CREDIT_BUREAU_WEEK      13.501631
AMT_REQ_CREDIT_BUREAU_MON       13.501631
AMT_REQ_CREDIT_BUREAU_QRT       13.501631
AMT_REQ_CREDIT_BUREAU_YEAR      13.501631
NAME_TYPE_SUITE                  0.420148
OBS_30_CNT_SOCIAL_CIRCLE         0.332021
DEF_30_CNT_SOCIAL_CIRCLE         0.332021
OBS_60_CNT_SOCIAL_CIRCLE         0.332021
DEF_60_CNT_SOCIAL_CIRCLE         0.332021
EXT_SOURCE_2                     0.214626
AMT_GOODS_PRICE                  0.090403
AMT_ANNUITY                      0.003902
CNT_FAM_MEMBERS                  0.000650
DAYS_LAST_PHONE_CHANGE           0.000325
CNT_CHILDREN                     0.000000
FLAG_DOCUMENT_8                  0.000000
NAME_CONTRACT_TYPE               0.000000
CODE_GENDER                      0.000000
FLAG_OWN_CAR                     0.000000
FLAG_DOCUMENT_2                  0.000000
FLAG_DOCUMENT_3                  0.000000
FLAG_DOCUMENT_4                  0.000000
FLAG_DOCUMENT_5                  0.000000
FLAG_DOCUMENT_6                  0.000000
FLAG_DOCUMENT_7                  0.000000
FLAG_DOCUMENT_9                  0.000000
FLAG_DOCUMENT_21                 0.000000
FLAG_DOCUMENT_10                 0.000000
FLAG_DOCUMENT_11                 0.000000
FLAG_OWN_REALTY                  0.000000
FLAG_DOCUMENT_13                 0.000000
FLAG_DOCUMENT_14                 0.000000
FLAG_DOCUMENT_15                 0.000000
FLAG_DOCUMENT_16                 0.000000
FLAG_DOCUMENT_17                 0.000000
FLAG_DOCUMENT_18                 0.000000
FLAG_DOCUMENT_19                 0.000000
FLAG_DOCUMENT_20                 0.000000
FLAG_DOCUMENT_12                 0.000000
AMT_CREDIT                       0.000000
AMT_INCOME_TOTAL                 0.000000
FLAG_PHONE                       0.000000
LIVE_CITY_NOT_WORK_CITY          0.000000
REG_CITY_NOT_WORK_CITY           0.000000
TARGET                           0.000000
REG_CITY_NOT_LIVE_CITY           0.000000
LIVE_REGION_NOT_WORK_REGION      0.000000
REG_REGION_NOT_WORK_REGION       0.000000
REG_REGION_NOT_LIVE_REGION       0.000000
HOUR_APPR_PROCESS_START          0.000000
WEEKDAY_APPR_PROCESS_START       0.000000
REGION_RATING_CLIENT_W_CITY      0.000000
REGION_RATING_CLIENT             0.000000
FLAG_EMAIL                       0.000000
FLAG_CONT_MOBILE                 0.000000
ORGANIZATION_TYPE                0.000000
FLAG_WORK_PHONE                  0.000000
FLAG_EMP_PHONE                   0.000000
FLAG_MOBIL                       0.000000
DAYS_ID_PUBLISH                  0.000000
DAYS_REGISTRATION                0.000000
DAYS_EMPLOYED                    0.000000
DAYS_BIRTH                       0.000000
REGION_POPULATION_RELATIVE       0.000000
NAME_HOUSING_TYPE                0.000000
NAME_FAMILY_STATUS               0.000000
NAME_EDUCATION_TYPE              0.000000
NAME_INCOME_TYPE                 0.000000
SK_ID_CURR                       0.000000
dtype: float64

In [9]:
num_cols = df.select_dtypes(exclude="object")

In [10]:
pd.set_option("display.float_format", lambda x: f"{x:.2f}")
pd.set_option("display.max_columns", None)
num_cols.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.00,307511.00,307511.00,307511.00,307511.00,307499.00,307233.00,307511.00,307511.00,307511.00,307511.00,307511.00,104582.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307509.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,134133.00,306851.00,246546.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,151450.00,127568.00,157504.00,103023.00,92646.00,143620.00,152683.00,154491.00,98869.00,124921.00,97312.00,153161.00,93997.00,137829.00,159080.00,306490.00,306490.00,306490.00,306490.00,307510.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,307511.00,265992.00,265992.00,265992.00,265992.00,265992.00,265992.00
mean,278180.52,0.08,0.42,168797.92,599026.00,27108.57,538396.21,0.02,-16037.00,63815.05,-4986.12,-2994.20,12.06,1.00,0.82,0.20,1.00,0.28,0.06,2.15,2.05,2.03,12.06,0.02,0.05,0.04,0.08,0.23,0.18,0.50,0.51,0.51,0.12,0.09,0.98,0.75,0.04,0.08,0.15,0.23,0.23,0.07,0.10,0.11,0.01,0.03,0.11,0.09,0.98,0.76,0.04,0.07,0.15,0.22,0.23,0.06,0.11,0.11,0.01,0.03,0.12,0.09,0.98,0.76,0.04,0.08,0.15,0.23,0.23,0.07,0.10,0.11,0.01,0.03,0.10,1.42,0.14,1.41,0.10,-962.86,0.00,0.71,0.00,0.02,0.09,0.00,0.08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.01,0.00,0.00,0.00,0.01,0.01,0.03,0.27,0.27,1.90
std,102790.18,0.27,0.72,237123.15,402490.78,14493.74,369446.46,0.01,4363.99,141275.77,3522.89,1509.45,11.94,0.00,0.38,0.40,0.04,0.45,0.23,0.91,0.51,0.50,3.27,0.12,0.22,0.20,0.27,0.42,0.38,0.21,0.19,0.19,0.11,0.08,0.06,0.11,0.08,0.13,0.10,0.14,0.16,0.08,0.09,0.11,0.05,0.07,0.11,0.08,0.06,0.11,0.07,0.13,0.10,0.14,0.16,0.08,0.10,0.11,0.05,0.07,0.11,0.08,0.06,0.11,0.08,0.13,0.10,0.15,0.16,0.08,0.09,0.11,0.05,0.07,0.11,2.40,0.45,2.38,0.36,826.81,0.01,0.45,0.01,0.12,0.28,0.01,0.27,0.06,0.00,0.06,0.00,0.06,0.05,0.03,0.10,0.02,0.09,0.02,0.02,0.02,0.08,0.11,0.20,0.92,0.79,1.87
min,100002.00,0.00,0.00,25650.00,45000.00,1615.50,40500.00,0.00,-25229.00,-17912.00,-24672.00,-7197.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,1.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-4292.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,189145.50,0.00,0.00,112500.00,270000.00,16524.00,238500.00,0.01,-19682.00,-2760.00,-7479.50,-4299.00,5.00,1.00,1.00,0.00,1.00,0.00,0.00,2.00,2.00,2.00,10.00,0.00,0.00,0.00,0.00,0.00,0.00,0.33,0.39,0.37,0.06,0.04,0.98,0.69,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.05,0.00,0.00,0.05,0.04,0.98,0.70,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.04,0.00,0.00,0.06,0.04,0.98,0.69,0.01,0.00,0.07,0.17,0.08,0.02,0.05,0.05,0.00,0.00,0.04,0.00,0.00,0.00,0.00,-1570.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,278202.00,0.00,0.00,147150.00,513531.00,24903.00,450000.00,0.02,-15750.00,-1213.00,-4504.00,-3254.00,9.00,1.00,1.00,0.00,1.00,0.00,0.00,2.00,2.00,2.00,12.00,0.00,0.00,0.00,0.00,0.00,0.00,0.51,0.57,0.54,0.09,0.08,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.08,0.07,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.09,0.08,0.98,0.76,0.02,0.00,0.14,0.17,0.21,0.05,0.08,0.07,0.00,0.00,0.07,0.00,0.00,0.00,0.00,-757.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00
75%,367142.50,0.00,1.00,202500.00,808650.00,34596.00,679500.00,0.03,-12413.00,-289.00,-2010.00,-1720.00,15.00,1.00,1.00,0.00,1.00,1.00,0.00,3.00,2.00,2.00,14.00,0.00,0.00,0.00,0.00,0.00,0.00,0.68,0.66,0.67,0.15,0.11,0.99,0.82,0.05,0.12,0.21,0.33,0.38,0.09,0.12,0.13,0.00,0.03,0.14,0.11,0.99,0.82,0.05,0.12,0.21,0.33,0.38,0.08,0.13,0.13,0.00,0.02,0.15,0.11,0.99,0.83,0.05,0.12,0.21,0.33,0.38,0.09,0.12,0.13,0.00,0.03,0.13,2.00,0.00,2.00,0.00,-274.00,0.00,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3.00
max,456255.00,1.00,19.00,117000000.00,4050000.00,258025.50,4050000.00,0.07,-7489.00,365243.00,0.00,0.00,91.00,1.00,1.00,1.00,1.00,1.00,1.00,20.00,3.00,3.00,23.00,1.00,1.00,1.00,1.00,1.00,1.00,0.96,0.85,0.90,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,348.00,34.00,344.00,24.00,0.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,4.00,9.00,8.00,27.00,261.00,25.00

In [11]:
df[df["DAYS_EMPLOYED"] == 365243]["TARGET"].value_counts(normalize= True)

TARGET
0   0.95
1   0.05
Name: proportion, dtype: float64

In [12]:
df[df["DAYS_EMPLOYED"] != 365243]["TARGET"].value_counts(normalize= True)

TARGET
0   0.91
1   0.09
Name: proportion, dtype: float64

In [22]:
df.select_dtypes(include="object").nunique().sort_values(ascending=False)

ORGANIZATION_TYPE             58
OCCUPATION_TYPE               18
NAME_INCOME_TYPE               8
NAME_TYPE_SUITE                7
WEEKDAY_APPR_PROCESS_START     7
WALLSMATERIAL_MODE             7
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
NAME_EDUCATION_TYPE            5
FONDKAPREMONT_MODE             4
CODE_GENDER                    3
HOUSETYPE_MODE                 3
NAME_CONTRACT_TYPE             2
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
EMERGENCYSTATE_MODE            2
dtype: int64

In [21]:
df["ORGANIZATION_TYPE"].nunique()

58

In [36]:
df["CODE_GENDER"].unique()

array(['M', 'F', 'XNA'], dtype=object)

In [40]:
df["FLAG_OWN_CAR"].unique()

array(['N', 'Y'], dtype=object)

##### Binary Yapılacak Kolonlar
NAME_CONTRACT_TYPE <p>
FLAG_OWN_CAR<p>
FLAG_OWN_REALTY<p>
EMERGENCYSTATE_MODE<p>

##### Nominal Yapılacak Kolonlar
ORGANIZATION_TYPE<p>
OCCUPATION_TYPE<p>
NAME_INCOME_TYPE<p>
NAME_TYPE_SUITE<p>
WEEKDAY_APPR_PROCESS_START<p>
WALLSMATERIAL_MODE<p>
NAME_FAMILY_STATUS<p>
NAME_HOUSING_TYPE<p>
FONDKAPREMONT_MODE<p>
CODE_GENDER<p>
HOUSETYPE_MODE<p>

In [51]:
num_cols = df.select_dtypes(exclude="object").columns

In [53]:
num_cols = [
    col for col in num_cols
    if df[col].nunique() <= 10
]

In [60]:
for col in num_cols:
    print(f"{col} ({df[col].nunique()} unique): {df[col].unique()}")

TARGET (2 unique): [1 0]
FLAG_MOBIL (2 unique): [1 0]
FLAG_EMP_PHONE (2 unique): [1 0]
FLAG_WORK_PHONE (2 unique): [0 1]
FLAG_CONT_MOBILE (2 unique): [1 0]
FLAG_PHONE (2 unique): [1 0]
FLAG_EMAIL (2 unique): [0 1]
REGION_RATING_CLIENT (3 unique): [2 1 3]
REGION_RATING_CLIENT_W_CITY (3 unique): [2 1 3]
REG_REGION_NOT_LIVE_REGION (2 unique): [0 1]
REG_REGION_NOT_WORK_REGION (2 unique): [0 1]
LIVE_REGION_NOT_WORK_REGION (2 unique): [0 1]
REG_CITY_NOT_LIVE_CITY (2 unique): [0 1]
REG_CITY_NOT_WORK_CITY (2 unique): [0 1]
LIVE_CITY_NOT_WORK_CITY (2 unique): [0 1]
DEF_30_CNT_SOCIAL_CIRCLE (10 unique): [ 2.  0.  1. nan  3.  4.  5.  6.  7. 34.  8.]
DEF_60_CNT_SOCIAL_CIRCLE (9 unique): [ 2.  0.  1. nan  3.  5.  4.  7. 24.  6.]
FLAG_DOCUMENT_2 (2 unique): [0 1]
FLAG_DOCUMENT_3 (2 unique): [1 0]
FLAG_DOCUMENT_4 (2 unique): [0 1]
FLAG_DOCUMENT_5 (2 unique): [0 1]
FLAG_DOCUMENT_6 (2 unique): [0 1]
FLAG_DOCUMENT_7 (2 unique): [0 1]
FLAG_DOCUMENT_8 (2 unique): [0 1]
FLAG_DOCUMENT_9 (2 unique): [0 1]
FLAG_DOCUMENT_10 (2 unique): [0 1]
FLAG_DOCUMENT_11 (2 unique): [0 1]
FLAG_DOCUMENT_12 (2 unique): [0 1]
FLAG_DOCUMENT_13 (2 unique): [0 1]
FLAG_DOCUMENT_14 (2 unique): [0 1]
FLAG_DOCUMENT_15 (2 unique): [0 1]
FLAG_DOCUMENT_16 (2 unique): [0 1]
FLAG_DOCUMENT_17 (2 unique): [0 1]
FLAG_DOCUMENT_18 (2 unique): [0 1]
FLAG_DOCUMENT_19 (2 unique): [0 1]
FLAG_DOCUMENT_20 (2 unique): [0 1]
FLAG_DOCUMENT_21 (2 unique): [0 1]
AMT_REQ_CREDIT_BUREAU_HOUR (5 unique): [ 0. nan  1.  2.  3.  4.]
AMT_REQ_CREDIT_BUREAU_DAY (9 unique): [ 0. nan  1.  3.  2.  4.  5.  6.  9.  8.]
AMT_REQ_CREDIT_BUREAU_WEEK (9 unique): [ 0. nan  1.  3.  2.  4.  5.  6.  8.  7.]

### Encode

In [64]:
df["AMT_INCOME_TOTAL"].describe().T

count      307511.00
mean       168797.92
std        237123.15
min         25650.00
25%        112500.00
50%        147150.00
75%        202500.00
max     117000000.00
Name: AMT_INCOME_TOTAL, dtype: float64

In [72]:
df["DECILE"] = pd.qcut(df["AMT_INCOME_TOTAL"], q = 10, labels = False, duplicates= "drop") +1

In [79]:
df.groupby("DECILE").agg(
    COUNT = ("TARGET", "count"),
    TARGET_RATE = ("TARGET", "mean"),
    INCOME_MEAN = ("AMT_INCOME_TOTAL", "mean")
)

        COUNT  TARGET_RATE  INCOME_MEAN
DECILE
1       33391         0.08     66254.12
2       30280         0.08     91089.28
3       36907         0.09    111333.28
4       48849         0.08    131852.49
5        4333         0.09    142953.06
6       31120         0.09    157141.51
7       30704         0.08    178061.63
8       44809         0.08    212733.50
9       19957         0.07    259491.09
10      27161         0.06    393910.39

#### Feature Engineering

In [80]:
df["INCOME/CREDIT"] = df["AMT_INCOME_TOTAL"] / df["AMT_CREDIT"]

In [81]:
df["ANNUITY/INCOME"] = df["AMT_ANNUITY"] / df["AMT_INCOME_TOTAL"]

In [82]:
df["CREDIT/ANNUITY"] = df["AMT_CREDIT"] / df["AMT_ANNUITY"]

In [84]:
df["DECILE_INC_CR"] = pd.qcut(df["INCOME/CREDIT"], q = 10, labels = False, duplicates= "drop") +1

In [85]:
df["DECILE_ANN_INC"] = pd.qcut(df["ANNUITY/INCOME"], q = 10, labels = False, duplicates= "drop") +1

In [86]:
df["DECILE_CR_ANN"] = pd.qcut(df["CREDIT/ANNUITY"], q = 10, labels = False, duplicates= "drop") +1

In [87]:
df.groupby("DECILE_INC_CR").agg(
    TARGET_RATE = ("TARGET", "mean"),
)

               TARGET_RATE
DECILE_INC_CR
1                     0.07
2                     0.07
3                     0.08
4                     0.09
5                     0.09
6                     0.09
7                     0.09
8                     0.08
9                     0.08
10                    0.07

In [90]:
df.groupby("DECILE_ANN_INC").agg(
    TARGET_RATE = ("TARGET", "mean"),
)

                TARGET_RATE
DECILE_ANN_INC
1.00                   0.07
2.00                   0.07
3.00                   0.08
4.00                   0.08
5.00                   0.08
6.00                   0.08
7.00                   0.09
8.00                   0.09
9.00                   0.09
10.00                  0.08

In [91]:
df.groupby("DECILE_CR_ANN").agg(
    TARGET_RATE = ("TARGET", "mean"),
)

               TARGET_RATE
DECILE_CR_ANN
1.00                  0.05
2.00                  0.11
3.00                  0.10
4.00                  0.10
5.00                  0.06
6.00                  0.14
7.00                  0.05
8.00                  0.07
9.00                  0.07
10.00                 0.06

In [98]:
df.groupby("DECILE_CR_ANN").agg(
    COUNT = ("TARGET", "count"),
    MIN = ("CREDIT/ANNUITY", "min"),
    MAX = ("CREDIT/ANNUITY", "max"),
    MEAN = ("CREDIT/ANNUITY", "mean"),
    TARGET_RATE = ("TARGET", "mean")
    
)

               COUNT   MIN   MAX  MEAN  TARGET_RATE
DECILE_CR_ANN
1.00           30763  8.04 10.52  9.57         0.05
2.00           30743 10.52 14.63 12.79         0.11
3.00           30793 14.63 17.77 15.96         0.10
4.00           30744 17.77 19.54 18.78         0.10
5.00           34068 19.54 20.00 19.94         0.06
6.00           27389 20.01 22.01 20.80         0.14
7.00           30754 22.01 25.21 23.66         0.05
8.00           31012 25.21 30.14 27.27         0.07
9.00           31423 30.14 34.06 32.14         0.07
10.00          29810 34.06 45.31 35.45         0.06