In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/selva86/datasets/master/Advertising.csv"
df = pd.read_csv(url)

In [3]:
df

     Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [18]:
X = df.drop(["sales", "Unnamed: 0"], axis = 1)

In [19]:
y = df["sales"]

In [20]:
X

        TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [21]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()

In [24]:
model.fit(X, y)

LinearRegression()

In [25]:
model.coef_ #b1, b2, b3 değerleri

array([ 0.04576465,  0.18853002, -0.00103749])

In [26]:
model.intercept_ #b0 değeri

np.float64(2.938889369459403)

In [28]:
model.predict([[460,85,65],[200,45,23]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([39.94824067, 20.55180688])

In [30]:
y_pred = model.predict(X)

In [31]:
list(zip(y, y_pred))

[(22.1, np.float64(20.523974409715173)),
 (10.4, np.float64(12.337854820894357)),
 (9.3, np.float64(12.307670779994224)),
 (18.5, np.float64(17.59782951168913)),
 (12.9, np.float64(13.188671856831292)),
 (7.2, np.float64(12.478347634035844)),
 (11.8, np.float64(11.729759951563684)),
 (13.2, np.float64(12.122953165502283)),
 (4.8, np.float64(3.7273408628615763)),
 (10.6, np.float64(12.550848722934688)),
 (8.6, np.float64(7.032299200558848)),
 (17.4, np.float64(17.28512918260028)),
 (9.2, np.float64(10.57712073362766)),
 (9.7, np.float64(8.826300480033197)),
 (19.0, np.float64(18.434366383561084)),
 (22.4, np.float64(20.819299516495466)),
 (12.5, np.float64(12.823656743699356)),
 (24.4, np.float64(23.224957158799022)),
 (11.3, np.float64(9.951682059118799)),
 (14.6, np.float64(14.166072932273266)),
 (18.0, np.float64(18.10076727708428)),
 (12.5, np.float64(14.740538200355454)),
 (5.6, np.float64(6.489150303563282)),
 (15.5, np.float64(16.545932895131465)),
 (9.7, np.float64(8.146518871822739)),
 (12.0, np.float64(15.610038604568869)),
 (15.0, np.float64(14.989514288403917)),
 (15.9, np.float64(17.051673435161685)),
 (18.9, np.float64(19.410538026572976)),
 (10.5, np.float64(9.144023893168718)),
 (21.4, np.float64(21.633933802695587)),
 (11.9, np.float64(11.346092904310973)),
 (9.6, np.float64(7.638883141827073)),
 (17.4, np.float64(18.864268292864367)),
 (9.5, np.float64(7.5748305147121195)),
 (12.8, np.float64(17.00682618184709)),
 (25.4, np.float64(23.405900517310013)),
 (14.7, np.float64(15.623477788695745)),
 (10.1, np.float64(9.908681034512185)),
 (21.5, np.float64(20.447610393747137)),
 (16.6, np.float64(16.377664671311138)),
 (17.1, np.float64(17.295983199388985)),
 (20.7, np.float64(21.59580325632196)),
 (12.9, np.float64(13.963856839972719)),
 (8.5, np.float64(8.887879956448518)),
 (14.9, np.float64(15.16152313852113)),
 (10.6, np.float64(8.873386732682395)),
 (23.2, np.float64(21.722629895028973)),
 (14.8, np.float64(16.263620181413813)),
 (9.7, np.float64(8.168165604405372)),
 (11.4, np.float64(12.631211324624607)),
 (10.7, np.float64(9.339812960643176)),
 (22.6, np.float64(20.66297562701452)),
 (21.2, np.float64(19.944699569642705)),
 (20.2, np.float64(20.37443007846128)),
 (23.7, np.float64(21.29261060374872)),
 (5.5, np.float64(8.527712544726835)),
 (13.2, np.float64(12.774588020808983)),
 (23.8, np.float64(21.898051982898814)),
 (18.4, np.float64(18.13348698070369)),
 (8.1, np.float64(5.742155584050594)),
 (24.2, np.float64(22.89067207993869)),
 (15.7, np.float64(16.784260729108627)),
 (14.0, np.float64(13.210692016950796)),
 (18.0, np.float64(16.977735563833622)),
 (9.3, np.float64(7.849045319482913)),
 (9.5, np.float64(9.016031632798812)),
 (13.4, np.float64(12.037007297677002)),
 (18.9, np.float64(18.97657924235419)),
 (22.3, np.float64(21.108912436143434)),
 (18.3, np.float64(17.7794978165823)),
 (12.4, np.float64(10.626938152945892)),
 (8.8, np.float64(10.366848810245017)),
 (11.0, np.float64(9.902982055592116)),
 (17.0, np.float64(17.329311966972654)),
 (8.7, np.float64(11.858321738983784)),
 (6.9, np.float64(4.477589040572707)),
 (14.2, np.float64(13.811902227800486)),
 (5.3, np.float64(8.813313526173587)),
 (11.0, np.float64(9.675303283274502)),
 (11.8, np.float64(11.445923639120624)),
 (12.3, np.float64(14.647940925761024)),
 (11.3, np.float64(10.17840799180992)),
 (13.6, np.float64(14.42184211915655)),
 (21.7, np.float64(20.7813646368339)),
 (15.2, np.float64(15.181407889846499)),
 (12.0, np.float64(11.598707394277248)),
 (16.0, np.float64(15.593784747966527)),
 (12.9, np.float64(11.711271005267472)),
 (16.7, np.float64(16.92225510676896)),
 (11.2, np.float64(9.99922965172348)),
 (7.3, np.float64(4.496315984459366)),
 (19.4, np.float64(19.15639616235322)),
 (22.2, np.float64(21.2275737847621)),
 (11.5, np.float64(10.482123854060982)),
 (16.9, np.float64(16.314921124994108)),
 (11.7, np.float64(12.635717161709083)),
 (15.5, np.float64(15.337077822510246)),
 (25.4, np.float64(24.118607229753366)),
 (17.2, np.float64(16.940350209868633)),
 (11.7, np.float64(13.8759584379728)),
 (23.8, np.float64(23.24248684858423)),
 (14.8, np.float64(17.644093845826696)),
 (14.7, np.float64(14.762211416061414)),
 (20.7, np.float64(20.30110878410441)),
 (19.2, np.float64(17.936414673257328)),
 (7.2, np.float64(6.126022148583049)),
 (8.7, np.float64(7.108502485117361)),
 (5.3, np.float64(3.5872584098050018)),
 (19.8, np.float64(19.692931062134043)),
 (13.4, np.float64(14.75987409511756)),
 (21.8, np.float64(21.140274980335334)),
 (14.1, np.float64(13.880609853211174)),
 (15.9, np.float64(16.40377622987127)),
 (14.6, np.float64(15.305095925878039)),
 (12.6, np.float64(12.919688951958426)),
 (12.2, np.float64(11.978747436893686)),
 (9.4, np.float64(6.5707773987576985)),
 (15.9, np.float64(15.566093478520513)),
 (6.6, np.float64(6.820067667138169)),
 (15.5, np.float64(14.410106047152569)),
 (7.0, np.float64(7.838076421805113)),
 (11.6, np.float64(13.626457100609537)),
 (15.2, np.float64(15.082790896662024)),
 (19.7, np.float64(19.45441306417943)),
 (10.6, np.float64(9.127349583004756)),
 (6.6, np.float64(10.577174114180362)),
 (8.8, np.float64(6.599668998991513)),
 (24.7, np.float64(22.2554916145396)),
 (9.7, np.float64(7.88410649148883)),
 (1.6, np.float64(10.427687101769537)),
 (12.7, np.float64(15.57779819246717)),
 (5.7, np.float64(8.449150116070706)),
 (19.6, np.float64(19.266923071099978)),
 (10.8, np.float64(11.836803896219829)),
 (11.6, np.float64(14.001413849249674)),
 (9.5, np.float64(11.45348626763253)),
 (20.8, np.float64(20.851251984902014)),
 (9.6, np.float64(9.768427954852235)),
 (20.7, np.float64(19.6754763186994)),
 (10.9, np.float64(9.489640973247123)),
 (19.2, np.float64(18.39902931906316)),
 (20.1, np.float64(19.249869267749126)),
 (10.4, np.float64(8.764802619866579)),
 (11.4, np.float64(10.091334033305756)),
 (10.3, np.float64(9.708538721613994)),
 (13.2, np.float64(15.294223677333727)),
 (25.4, np.float64(23.260861031422433)),
 (10.9, np.float64(12.263359411362687)),
 (10.1, np.float64(9.827271101130345)),
 (16.1, np.float64(18.36720534138094)),
 (11.6, np.float64(10.009537700506844)),
 (16.6, np.float64(16.36000030443698)),
 (19.0, np.float64(18.223901319920387)),
 (15.6, np.float64(15.501616959053672)),
 (3.2, np.float64(5.307558901735591)),
 (15.3, np.float64(15.384851915018087)),
 (10.1, np.float64(10.014311199739463)),
 (7.3, np.float64(10.384198660049375)),
 (12.9, np.float64(12.399148227960556)),
 (14.4, np.float64(14.213832980330979)),
 (13.3, np.float64(13.559145683664623)),
 (14.9, np.float64(14.946782057588429)),
 (18.0, np.float64(17.35163607549252)),
 (11.9, np.float64(11.068294603100242)),
 (11.9, np.float64(14.223721376270058)),
 (8.0, np.float64(10.824395309518025)),
 (12.2, np.float64(13.36324677258626)),
 (17.1, np.float64(17.18614280057505)),
 (15.0, np.float64(17.941556296290074)),
 (8.4, np.float64(7.394979966498894)),
 (14.5, np.float64(14.358273730249415)),
 (7.6, np.float64(7.607692378719012)),
 (11.7, np.float64(11.970938873323922)),
 (11.5, np.float64(13.744357417405295)),
 (27.0, np.float64(24.786870314183705)),
 (20.2, np.float64(19.979372702747686)),
 (11.7, np.float64(12.162046402834912)),
 (11.8, np.float64(16.010997220773113)),
 (12.6, np.float64(12.384554948507716)),
 (10.5, np.float64(10.587199699509453)),
 (12.2, np.float64(13.928099183458244)),
 (8.7, np.float64(6.554669997124972)),
 (26.2, np.float64(24.133100129464765)),
 (17.6, np.float64(18.53852095512279)),
 (22.6, np.float64(20.80301058719441)),
 (10.3, np.float64(9.691373131085735)),
 (17.3, np.float64(17.07644222816529)),
 (15.9, np.float64(18.64430648060901)),
 (6.7, np.float64(6.051624106991669)),
 (10.8, np.float64(12.489159100639455)),
 (9.9, np.float64(8.424019325803677)),
 (5.9, np.float64(4.466229560514631)),
 (19.6, np.float64(18.486957967031408)),
 (17.3, np.float64(16.495300438165653)),
 (7.6, np.float64(5.370342484466777)),
 (9.7, np.float64(8.165312360613004)),
 (12.8, np.float64(12.78592081693224)),
 (25.5, np.float64(23.76732149176284)),
 (13.4, np.float64(15.173195535684213))]

In [34]:
np.mean((y-y_pred)**2)

np.float64(2.784126314510936)

In [35]:
from sklearn.metrics import mean_squared_error

In [36]:
mean_squared_error(y, y_pred)

2.784126314510936

In [41]:
np.mean((y-np.mean(y))**2)

np.float64(27.085743750000002)

In [42]:
1-2.784126314510936/27.085743750000002

0.8972106381789522